### PR TITLE
fix: allow ip v4 and v6 in log test

### LINKED ISSUE #49234: Support IPv6 in logger test or force IPv4 in boilerplate-express
### Describe the Issue

The issue is related to Node.js versions 17+ and running the "Basic Node and Express - Implement a Root-Level Request Logger" challenge on localhost. The IP in the logger regex test is expected to be an IPv4 address.

https://github.com/nodejs/node/issues/40537

> Node.js now returns IP addresses in the order they are returned from the name resolver/DNS.

## Option 1

Change the regex in wrappers.js

https://github.com/freeCodeCamp/fcc-express-bground-pkg/blob/main/wrappers.js#L45

to support both IPv4 (as it does now)

```
GET /json - ::ffff:127.0.0.1
```

and the IPv6 localhost abbreviation

```
GET /json - ::1
```

I'm not sure how thorough a regex we should use. Does it need to cover all possible IPs?

## Option 2

Force IPv4 in server.js

https://github.com/freeCodeCamp/boilerplate-express/blob/main/server.js

```
const dns = require('dns');
dns.setDefaultResultOrder('ipv4first');
```

Tested and working.

### Affected Page

https://www.freecodecamp.org/learn/back-end-development-and-apis/basic-node-and-express/implement-a-root-level-request-logger-middleware

### Your code

```

```

### Expected behavior

Logger test to pass on localhost with Node versions 17+

### Screenshots

_No response_

### System

- Device: [Laptop/Desktop]
- OS: [Windows 10]
- Browser: [Chrome]

### Additional context

https://forum.freecodecamp.org/t/basic-node-and-express-implement-a-root-level-request-logger-middleware/580132/3

### PR DESCRIPTION
**Pull request by a2937**
Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes freeCodeCamp/freeCodeCamp#49234 

I also added a gitignore, an editorconfig, a prettier file, and a prettier ignore file since it is the standard.

### CODE REVIEW

**Review by ShaunSHamilton — CHANGES_REQUESTED** [review]
Please remove all changes expect those relating to fixing the linked issue. Also, we do not use PNPM for this boilerplate.

**Comment by a2937** [comment]
Understood. I have removed the extra unnecessary files. But as did add a node_module as specified by the issue, I think having the gitignore is a good idea.

**Comment by lasjorg** [comment]
> But as did add a node_module as specified by the issue, I think having the gitignore is a good idea.

Then I'd prefer if you just gitignore the node_modules folder, that gitignore file seems a little over the top.

Also, as far as I can tell when I tested it, the `ip` dependency will not be inside the `fcc-express-bground-pkg` lib folder when installing the `boilerplate-express` dependencies. So I'm not sure we really need a gitignore at all.

---

Other than that I tested it and it looks to be working.

1. Cloned the test lib down, made the changes, and push the lib to my own repo.

2. Cloned boilerplate-express, change the lib dependency URL to my own repo, and install the dependencies.

3. Ran the test using localhost, passing.

4. Made the same update to a Replit and ran the test, passing.

**Comment by ShaunSHamilton** [comment]
I agree with @lasjorg .

Except, we should keep a `.gitignore` for when more changes/tests are made with this repo. That way, contributors will not accidentally commit the `node_modules` folder.

---

@a2937 Please remove everything except `node_modules` from the `.gitignore`.

I understand these changes are minute and tedious. So, if you want, we can take over this PR from here to get it in?

**Comment by lasjorg** [comment]
@ShaunSHamilton I'm totally fine with having a reasonable gitignore file.

I just thought I'd mention that the dependency does not seem to get installed to the lib root when installed as it would be by the camper.

**Review by ShaunSHamilton — APPROVED** [review]
This looks good to me 👍 

Congrats on your first pull request (PR) to this repo! 🎉

Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝

**Review by lasjorg — APPROVED** [review]
LGTM

**Pull request merged**
